name: rdflint
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  rdflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: imas/setup-rdflint@v1
    - name: Run rdflint
      run: rdflint -config .rdflint/rdflint-config.yml
