name: rdflint
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  rdflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - uses: imas/setup-rdflint@v2
    - name: Run rdflint
      run: rdflint -config .rdflint/rdflint-config.yml
